apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgcmVjZWl2ZXI6IHdlYmhvb2sKICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDMwbQogIGdyb3VwX2J5OiBbJ2FsZXJ0bmFtZSddCiAgcm91dGVzOgogIC0gcmVjZWl2ZXI6IHdlYmhvb2sKICAgIGdyb3VwX3dhaXQ6IDEwcwpyZWNlaXZlcnM6Ci0gbmFtZTogd2ViaG9vawogIHdlYmhvb2tfY29uZmlnczoKICAtIHVybDogaHR0cDovLzEwLjExNS4xNDMuMjIyOjgwNjEvZGluZ3RhbGsvb3BzX2RpbmdkaW5nL3NlbmQKICAgIHNlbmRfcmVzb2x2ZWQ6IHRydWUK
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
