kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-AddressType: "intranet"
  labels:
    app: prometheus
  name: prometheus
  namespace: monitor
spec:
  type: LoadBalancer
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
