{
 "title": "Go gRPC",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(grpc_server_handled_total,job)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "le",
    "query": "\"0.1\",\"0.15\",\"0.25\",\"0.3\",\"0.5\",\"1\""
   },
   {
    "name": "grpc_service",
    "query": "label_values(grpc_server_handled_total,grpc_service) "
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"OK\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"NotFound\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\"}[$interval])))\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{job=\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "gRPC request code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grpc_server_started_total{job=\"$job\"}[$interval])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Average handling time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(grpc_server_handling_seconds_sum{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "$grpc_service gRPC requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "grpc_service",
   "collapsed": true,
   "panels": [
    {
     "title": "QPS",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "format": "ops",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Global Success Rate",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"NotFound\",grpc_service=~\"$grpc_service\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"PermissionDenied\",grpc_service=~\"$grpc_service\"}[$interval])) + \nsum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_code=\"InvalidArgument\",grpc_service=~\"$grpc_service\"}[$interval])))\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_type=\"unary\",grpc_service=~\"$grpc_service\"}[$interval]))"
      }
     ]
    },
    {
     "title": "gRPC request code",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "QPS by method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "99%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request error percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_code!=\"OK\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n/ \nsum(rate(grpc_server_started_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Request count per pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "90%-tile latency of requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method,le)\n)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Percentage of slow queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100.0 - (\nsum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",le=\"$le\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n / \nsum(rate(grpc_server_handling_seconds_count{job=\"$job\",grpc_service=~\"$grpc_service\"}[$interval])) by (grpc_method)\n) * 100.0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  }
 ]
}