{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes, kubernetes_namespace)"
   },
   {
    "name": "app",
    "query": "label_values(process_resident_memory_bytes{kubernetes_namespace=~\"$namespace\"},app)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - resident"
    }
   ]
  },
  {
   "title": "GC rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC pause per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{kubernetes_namespace=~\"^($namespace)$\",app=~\"^($app)$\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}