apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: nginx-internal
  name: prometheus-ing
  namespace: monitoring
spec:
  rules:
  - host: prometheus-pro.shimo.run
    http:
      paths:
      - backend:
          serviceName: prometheus-k8s
          servicePort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: nginx-internal
  name: grafana-ing
  namespace: monitoring
spec:
  rules:
  - host: grafana-pro.shimo.run
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: nginx-internal
  name: alertmanager-ing
  namespace: monitoring
spec:
  rules:
  - host: alertmanager-pro.shimo.run
    http:
      paths:
      - backend:
          serviceName: alertmanager-main
          servicePort: 9093

